### PR TITLE
Added shared-notes from cohort3 to databases

### PR DESCRIPTION
**Pull request by SirajB**
TODO: Pretty shared-notes file

### CODE REVIEW

**Comment by SirajB** [comment]
> Thanks so much for this! The rendered view looks a little wonky though: https://github.com/adaapp/digital-innovation/blob/8799dd2b017abd01ffe66bdf03e825a442123628/modules/year-1/dat/shared-notes.md
> 
> Are you able to fix the formatting? I don't have time to get this sorted at the moment, unfortunately.

Hopefully fixed

**Comment by SirajB** [comment]
Yup looks like it's all fixed! Merge away!

**Comment by SirajB** [comment]
Okay now it should be all fixed my bad!

**Comment by SomeHats** [comment]
Amazing, thanks Siraj!

**Pull request merged**
